/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exampractice;

import javax.swing.JOptionPane;

/**
 *
 * @author tvnmt
 */
public class Musical_Lessons extends javax.swing.JFrame {
    public static double[][] lessonPrices = new double[][] {{150,250,280},{215,232,280},{130,185,310}}; 
    /**
     * Creates new form Musical_Lessons
     */
    public Musical_Lessons() {
        initComponents();
    }
    public static double AvgPrice( int level)
    {   int TotalPrice =0; 
        int AvgPrice =0; 
        for (int i = 0; i <  lessonPrices[level].length ; i++) {
             TotalPrice += lessonPrices[level][i];
        }
        AvgPrice = TotalPrice/ lessonPrices[level].length ;
       return AvgPrice;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnReport = new javax.swing.JButton();
        BtnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CmbLevel = new javax.swing.JComboBox<>();
        CmbInstrument = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MItmExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MItmSubmit = new javax.swing.JMenuItem();
        MItmReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnReport.setText("REPORT");
        BtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportActionPerformed(evt);
            }
        });

        BtnSubmit.setText("SUBMIT");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("LEVEL:");

        jLabel2.setText("INSTRUMENT:");

        CmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Intermediate", "Advanced" }));
        CmbLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbLevelActionPerformed(evt);
            }
        });

        CmbInstrument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "Piano", "Violin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbInstrument, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(BtnReport)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CmbInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSubmit)
                            .addComponent(BtnReport)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(124, 124, 124))
        );

        jMenu1.setText("File");

        MItmExit.setText("Exit");
        MItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItmExitActionPerformed(evt);
            }
        });
        jMenu1.add(MItmExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        MItmSubmit.setText("Submit");
        MItmSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItmSubmitActionPerformed(evt);
            }
        });
        jMenu2.add(MItmSubmit);

        MItmReport.setText("Report");
        MItmReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItmReportActionPerformed(evt);
            }
        });
        jMenu2.add(MItmReport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmbLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbLevelActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
      String output ="";
        double price = 0;
        int InstrumentIndex;
        int LevelIndex;        
        LevelIndex =  CmbLevel.getSelectedIndex();
        InstrumentIndex =  CmbInstrument.getSelectedIndex();
        
         price = lessonPrices[LevelIndex][InstrumentIndex];
         output ="\nInstrument: "+CmbInstrument.getItemAt(InstrumentIndex)
                 +" \nLevel: "+CmbLevel.getItemAt(LevelIndex)
                 +" \nLesson Price: R"+price;
         JOptionPane.showMessageDialog(null,output);
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void MItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItmExitActionPerformed
        // Exit the application
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_MItmExitActionPerformed

    private void MItmSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItmSubmitActionPerformed
        String output ="";
        double price = 0;
        int InstrumentIndex;
        int LevelIndex;        
        LevelIndex =  CmbLevel.getSelectedIndex();
        InstrumentIndex =  CmbInstrument.getSelectedIndex();
        
         price = lessonPrices[LevelIndex][InstrumentIndex];
         output ="\nInstrument: "+CmbInstrument.getItemAt(InstrumentIndex)
                 +" \nLevel: "+CmbLevel.getItemAt(LevelIndex)
                 +" \nLesson Price: R"+price;
         JOptionPane.showMessageDialog(null,output);
// TODO add your handling code here:
    }//GEN-LAST:event_MItmSubmitActionPerformed

    private void BtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportActionPerformed
        String output ="";
        double price = 0;
      
        for (int i = 0; i < lessonPrices.length; i++) {
            price =  price = AvgPrice(i);
            output +="\nAverage lesson price for "+ CmbLevel.getItemAt(i)+" R "+price;
        }
    JOptionPane.showMessageDialog(null,output);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReportActionPerformed

    private void MItmReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItmReportActionPerformed
        String output ="";
        double price = 0;

        for (int i = 0; i < lessonPrices.length; i++) {
            price = AvgPrice(i);
            output +="\nAverage lesson price for "+ CmbLevel.getItemAt(i)+" R "+price;
        }
    JOptionPane.showMessageDialog(null,output);
        // TODO add your handling code here:
    }//GEN-LAST:event_MItmReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musical_Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musical_Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musical_Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musical_Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musical_Lessons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReport;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox<String> CmbInstrument;
    private javax.swing.JComboBox<String> CmbLevel;
    private javax.swing.JMenuItem MItmExit;
    private javax.swing.JMenuItem MItmReport;
    private javax.swing.JMenuItem MItmSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
