/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exampractice3;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.Buffer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.xml.catalog.CatalogException;

/**
 *
 * @author tvnmt
 */
public class SnakeInformation extends javax.swing.JFrame {

    /**
     * Creates new form SnakeInformation
     */
    public SnakeInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlSnakeInfo = new javax.swing.JPanel();
        CmbxSnake = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnProcess = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaMedicalInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlSnakeInfo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PnlSnakeInfoComponentAdded(evt);
            }
        });
        PnlSnakeInfo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PnlSnakeInfoComponentShown(evt);
            }
        });

        CmbxSnake.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CmbxSnakeComponentAdded(evt);
            }
        });
        CmbxSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbxSnakeActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Snake");

        BtnProcess.setText("PROCESS");
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });

        BtnClear.setText("CLEAR");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        TxtAreaMedicalInfo.setColumns(20);
        TxtAreaMedicalInfo.setRows(5);
        jScrollPane1.setViewportView(TxtAreaMedicalInfo);

        javax.swing.GroupLayout PnlSnakeInfoLayout = new javax.swing.GroupLayout(PnlSnakeInfo);
        PnlSnakeInfo.setLayout(PnlSnakeInfoLayout);
        PnlSnakeInfoLayout.setHorizontalGroup(
            PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSnakeInfoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSnakeInfoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CmbxSnake, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSnakeInfoLayout.createSequentialGroup()
                            .addComponent(BtnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        PnlSnakeInfoLayout.setVerticalGroup(
            PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSnakeInfoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbxSnake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(PnlSnakeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnProcess)
                    .addComponent(BtnClear))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlSnakeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlSnakeInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        TxtAreaMedicalInfo.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        // TODO add your handling code here:
        
        int CmbxIndex = CmbxSnake.getSelectedIndex();
        String output= TxtAreaMedicalInfo.getText();
        output+= CmbxSnake.getItemAt(CmbxIndex) +"\n"+FatalityRanking.get(CmbxIndex)
                +"\n"+MedicalAssistance.get(CmbxIndex);
        
        TxtAreaMedicalInfo.setText(output+"\n\n");
    }//GEN-LAST:event_BtnProcessActionPerformed

    private void CmbxSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbxSnakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbxSnakeActionPerformed

    private void PnlSnakeInfoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PnlSnakeInfoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PnlSnakeInfoComponentShown

    private void PnlSnakeInfoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PnlSnakeInfoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PnlSnakeInfoComponentAdded

    private void CmbxSnakeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CmbxSnakeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbxSnakeComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnakeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnakeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnakeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnakeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnakeInformation().setVisible(true);
            }
        });
         readSnakeInfo();
    }
    public static ArrayList<String> FatalityRanking = new ArrayList<String>() ;
    public static ArrayList<String> MedicalAssistance = new ArrayList<String>() ;
   // public static ArrayList<String> SnakeType = new ArrayList<String>();

    public static void readSnakeInfo() {
        FileReader fr;
        try {
            fr = new FileReader("C:\\Users\\tvnmt\\OneDrive\\Desktop\\snakes.txt");
            BufferedReader buff = new BufferedReader(fr);
            String snakeType;
            String fatalityRanking;
            String medicalAssistance;
            
            snakeType = buff.readLine();
            
            while ( snakeType != null) {
            // snakeType = buff.readLine();
            //System.out.println(snakeType);
            JOptionPane.showMessageDialog(null, "loading "+snakeType+" to combo box");
            CmbxSnake.addItem(snakeType);
            fatalityRanking = buff.readLine();
            FatalityRanking.add(fatalityRanking);
            medicalAssistance = buff.readLine();
            MedicalAssistance.add(medicalAssistance);
            snakeType = buff.readLine();
            } 
            buff.close();
            fr.close();
           // loadCmbx(); 
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(PnlSnakeInfo, "File not found");
        } catch (IOException ex)
        {
             JOptionPane.showMessageDialog(PnlSnakeInfo, "File not found");
        }

    }
    /*public static void loadCmbx()
    {   for (String snake : SnakeType) {
            CmbxSnake.addItem(snake);
        }
          
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnProcess;
    private static javax.swing.JComboBox<String> CmbxSnake;
    private static javax.swing.JPanel PnlSnakeInfo;
    private javax.swing.JTextArea TxtAreaMedicalInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
